/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CBtn: typeof import('./src/core/components/CBtn.vue')['default']
    CContainer: typeof import('./src/core/components/CContainer.vue')['default']
    CHeader: typeof import('./src/core/components/CHeader.vue')['default']
    DefaultDrawer: typeof import('./src/layouts/components/default/DefaultDrawer.vue')['default']
    DefaultHeader: typeof import('./src/layouts/components/default/DefaultHeader.vue')['default']
    NavLinks: typeof import('./src/layouts/components/NavLinks.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
